Add prebuilt drivers configs for ubuntu generic kernel 5.12.3-arch1-1 1
falcosecurity/test-infra pull request #466
Opened 2021-07-16 09:38 UTC by gauravgahlot

Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>

2021-07-16 09:38 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/test-infra/pull/466#" title="Author self-approved">gauravgahlot</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leogr** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leogr` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-07-16 09:38 UTC, poiana commented
Welcome @gauravgahlot! It looks like this is your first PR to falcosecurity/test-infra 🎉

2021-07-16 09:38 UTC, poiana commented
Hi @gauravgahlot. Thanks for your PR.

I'm waiting for a [falcosecurity](https://github.com/orgs/falcosecurity/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ftest-infra).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-07-16 09:40 UTC, gauravgahlot commented
/assign

2021-07-16 10:00 UTC, leogr commented
/ok-to-test

2021-07-16 14:07 UTC, leogr commented
/retest build-drivers-ubuntu-generic-5-presubmit

2021-07-16 14:07 UTC, poiana commented
@leogr: The `/retest` command does not accept any targets.
The following commands are available to trigger jobs:
* `/test build-drivers-amazonlinux-presubmit`
* `/test build-drivers-amazonlinux2-presubmit`
* `/test build-images-autobump`
* `/test build-images-build-drivers`
* `/test build-images-golang`
* `/test build-images-update-jobs`
* `/test build-images-update-maintainers`
* `/test build-images-build-libs`
* `/test build-images-update-falco-k8s-manifests`
* `/test build-drivers-centos-presubmit`
* `/test check-prow-config`
* `/test build-drivers-debian-presubmit`
* `/test build-drivers-ubuntu-aws-3-presubmit`
* `/test build-drivers-ubuntu-aws-4-presubmit`
* `/test build-drivers-ubuntu-aws-5-presubmit`
* `/test build-drivers-ubuntu-generic-3-presubmit`
* `/test build-drivers-ubuntu-generic-4-presubmit`
* `/test build-drivers-ubuntu-generic-5-presubmit`

Use `/test all` to run the following jobs:
* `check-prow-config`
* `build-drivers-ubuntu-generic-3-presubmit`
* `build-drivers-ubuntu-generic-4-presubmit`
* `build-drivers-ubuntu-generic-5-presubmit`



<details>

In response to [this](https://github.com/falcosecurity/test-infra/pull/466#issuecomment-881477267):

>/retest build-drivers-ubuntu-generic-5-presubmit


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-07-16 14:35 UTC, leogr commented
> @leogr: The `/retest` command does not accept any targets.

@poiana , sorry :pray: 

/test build-drivers-ubuntu-generic-5-presubmit

:smile_cat:

2021-07-19 12:54 UTC, leogr commented
/test build-drivers-ubuntu-generic-5-presubmit

2021-07-19 13:12 UTC, poiana commented
@gauravgahlot: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-drivers-ubuntu-generic-5-presubmit | 890a68acc5bafa369d4ee3cd8f7aac488518177f | [link](http://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/466/build-drivers-ubuntu-generic-5-presubmit/1417105462691631104) | `/test build-drivers-ubuntu-generic-5-presubmit`

[Full PR test history](http://prow.falco.org/pr-history?org=falcosecurity&repo=test-infra&pr=466). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/falcosecurity/test-infra/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-07-19 14:00 UTC, gauravgahlot commented
@leogr Is there anything I can do to fix the tests?

2021-07-20 08:11 UTC, maxgio92 commented
Hey @gauravgahlot, we're checking

2021-07-20 08:31 UTC, maxgio92 requested changes
Hey @gauravgahlot, thank you. I left some suggestions, as the `kernelrelease` in the Driverkit config should contain the kernel release only, without the version (as for `uname -r`) :)

2021-07-20 08:31 UTC, maxgio92 commented on driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.12.3-arch1-1_1.yaml
> +kernelrelease: 5.12.3-arch1-1_1
```suggestion
kernelrelease: 5.12.3-arch1-1
```

2021-07-20 08:31 UTC, maxgio92 commented on driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.12.3-arch1-1_1.yaml
> +kernelrelease: 5.12.3-arch1-1_1
```suggestion
kernelrelease: 5.12.3-arch1-1
```

2021-07-20 08:31 UTC, maxgio92 commented on driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.12.3-arch1-1_1.yaml
> +kernelrelease: 5.12.3-arch1-1_1
```suggestion
kernelrelease: 5.12.3-arch1-1
```

2021-07-20 08:31 UTC, maxgio92 commented on driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.12.3-arch1-1_1.yaml
> +kernelrelease: 5.12.3-arch1-1_1
```suggestion
kernelrelease: 5.12.3-arch1-1
```

2021-07-20 08:31 UTC, maxgio92 commented on driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.12.3-arch1-1_1.yaml
> +kernelrelease: 5.12.3-arch1-1_1
```suggestion
kernelrelease: 5.12.3-arch1-1
```

2021-07-20 12:07 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/test-infra/pull/466#" title="Author self-approved">gauravgahlot</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **maxgio92** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["maxgio92"]} -->

2021-07-20 12:08 UTC, gauravgahlot commented
Thank you @maxgio92. I have made the suggested changes. :rocket:

2021-07-21 07:45 UTC, maxgio92 approved these changes
/approve

Thank you @gauravgahlot! :)

2021-07-21 07:45 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 4b240f2db611c6958194ba19472c7f796839ba80</details>

2021-07-21 07:45 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/test-infra/pull/466#" title="Author self-approved">gauravgahlot</a>*, *<a href="https://github.com/falcosecurity/test-infra/pull/466#pullrequestreview-711352875" title="Approved">maxgio92</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/test-infra/blob/master/OWNERS)~~ [maxgio92]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-07-21 07:46 UTC, merged